import 'package:flutter/widgets.dart';
import 'package:lucide_icons/lucide_icons.dart';

/// Maps the string icon keys used across mock data to outline Lucide icons.
/// (Lucide ≈ the "thin, soft, iOS-like" set specified in the handoff.)
IconData appIcon(String name) {
  switch (name) {
    // event types
    case 'syringe':
      return LucideIcons.syringe;
    case 'pill':
      return LucideIcons.pill;
    case 'stethoscope':
      return LucideIcons.stethoscope;
    case 'flask':
      return LucideIcons.flaskConical;
    case 'weight':
      return LucideIcons.scale;
    case 'bug':
      return LucideIcons.bug;
    case 'scissors':
      return LucideIcons.scissors;
    case 'walk':
      return LucideIcons.footprints;
    case 'bowl':
      return LucideIcons.utensils;
    case 'notes':
      return LucideIcons.stickyNote;
    case 'image':
      return LucideIcons.image;
    // health
    case 'thermometer':
      return LucideIcons.thermometer;
    case 'flame':
      return LucideIcons.flame;
    case 'heart':
      return LucideIcons.heart;
    case 'activity':
      return LucideIcons.activity;
    case 'scale':
      return LucideIcons.scale;
    // care
    case 'droplet':
      return LucideIcons.droplet;
    case 'tooth':
      return LucideIcons.sparkles;
    case 'paw':
      return LucideIcons.scissors;
    case 'ear':
      return LucideIcons.ear;
    case 'toilet':
      return LucideIcons.bath;
    case 'bed':
      return LucideIcons.bed;
    case 'smile':
      return LucideIcons.smile;
    // chrome / ui
    case 'bell':
      return LucideIcons.bell;
    case 'bellRing':
      return LucideIcons.bellRing;
    case 'calendar':
      return LucideIcons.calendar;
    case 'clock':
      return LucideIcons.clock;
    case 'camera':
      return LucideIcons.camera;
    case 'document':
    case 'fileText':
      return LucideIcons.fileText;
    case 'file':
      return LucideIcons.file;
    case 'fileCheck':
      return LucideIcons.fileCheck;
    case 'folder':
      return LucideIcons.folder;
    case 'cloud':
      return LucideIcons.cloud;
    case 'uploadCloud':
      return LucideIcons.uploadCloud;
    case 'download':
      return LucideIcons.download;
    case 'shield':
      return LucideIcons.shield;
    case 'shieldCheck':
      return LucideIcons.shieldCheck;
    case 'fingerprint':
      return LucideIcons.fingerprint;
    case 'faceId':
      return LucideIcons.scanFace;
    case 'lock':
      return LucideIcons.lock;
    case 'globe':
      return LucideIcons.globe;
    case 'moon':
      return LucideIcons.moon;
    case 'sun':
      return LucideIcons.sun;
    case 'settings':
      return LucideIcons.settings;
    case 'user':
      return LucideIcons.user;
    case 'tag':
      return LucideIcons.tag;
    case 'ruler':
      return LucideIcons.ruler;
    case 'gauge':
      return LucideIcons.gauge;
    case 'trendingUp':
      return LucideIcons.trendingUp;
    case 'sparkles':
      return LucideIcons.sparkles;
    case 'star':
      return LucideIcons.star;
    case 'gift':
      return LucideIcons.gift;
    case 'list':
      return LucideIcons.list;
    case 'grid':
      return LucideIcons.layoutGrid;
    // navigation glyphs
    case 'chevronRight':
      return LucideIcons.chevronRight;
    case 'chevronLeft':
      return LucideIcons.chevronLeft;
    case 'chevronDown':
      return LucideIcons.chevronDown;
    case 'chevronUp':
      return LucideIcons.chevronUp;
    case 'arrowLeft':
      return LucideIcons.arrowLeft;
    case 'arrowRight':
      return LucideIcons.arrowRight;
    case 'plus':
      return LucideIcons.plus;
    case 'plusCircle':
      return LucideIcons.plusCircle;
    case 'check':
      return LucideIcons.check;
    case 'checkCircle':
      return LucideIcons.checkCircle;
    case 'x':
      return LucideIcons.x;
    case 'search':
      return LucideIcons.search;
    case 'filter':
      return LucideIcons.listFilter;
    case 'edit':
      return LucideIcons.pencil;
    case 'trash':
      return LucideIcons.trash2;
    case 'share':
      return LucideIcons.share2;
    case 'retry':
      return LucideIcons.rotateCcw;
    case 'wifi':
      return LucideIcons.wifi;
    case 'wifiOff':
      return LucideIcons.wifiOff;
    // species
    case 'cat':
      return LucideIcons.cat;
    case 'dog':
      return LucideIcons.dog;
    case 'bird':
      return LucideIcons.bird;
    case 'fish':
      return LucideIcons.fish;
    default:
      return LucideIcons.circle;
  }
}
